version: "3.7"
services:

  spark-master:
    image: rodrago/spark-master-hadoop:2.4.6
    container_name: spark-master
    hostname: spark-master
    tty: true
    volumes:
      - ./user_data:/user_data
      - spark-master-data:/usr/hadoop-2.7.3/data
      - spark-master-logs:/usr/hadoop-2.7.3/logs

    ports:
      - "8088:8088" # ResourceManager
      - "11070:50070" # NameNode WebUI
      - "10015:10015" # HDFS
      - "8080:8080" # WebUI Spark Master
      - "8042:8042" # NodeManager
      - "8888:8888" # Jupyter
      - "4040:4040" # Spark
      - "7077:7077" # Spark Master
      - "11000:10000" # HiveServer2 - Binary Mode
      - "11001:10001" # HiveServer - HTTP Mode
      - "11002:10002" # Hiveserver WebUI
      - "9092:9092" # Kafka
      - "9000:9000" # Default FS
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
    environment:
      - "SPARK_LOCAL_IP=spark-master"

  spark-worker-1:
    image: rodrago/spark-worker-hadoop:2.4.6
    container_name: spark-worker-1
    hostname: spark-worker-1
    tty: true
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # WebUI Spark worker
      - "6042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks:
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
      - spark-worker-1-data:/usr/hadoop-2.7.3/data
      - spark-worker-1-logs:/usr/hadoop-2.7.3/logs

  spark-worker-2:
    image: rodrago/spark-worker-hadoop:2.4.6
    container_name: spark-worker-2
    hostname: spark-worker-2
    tty: true
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # WebUI Spark worker
      - "7042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks:
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
      - spark-worker-2-data:/usr/hadoop-2.7.3/data
      - spark-worker-2-logs:/usr/hadoop-2.7.3/logs

volumes:
  spark-master-data:
    name: "spark-master-data"
  spark-worker-1-data:
    name: "spark-worker-1-data"
  spark-worker-2-data:
    name: "spark-worker-2-data"
  spark-master-logs:
    name: "spark-master-logs"
  spark-worker-1-logs:
    name: "spark-worker-1-logs"
  spark-worker-2-logs:
    name: "spark-worker-2-logs"


networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
  # spark-network:
  # driver: overlay
  #   ipam:
  #     config:
  #       - subnet: 10.5.0.0/16
